export default {
  // Action types
  SEARCH_BOOKS: 'SEARCH_BOOKS',
  SELECT_BOOK: 'SELECT_BOOK',
  ADD_BOOK: 'ADD_BOOK',
  BORROW_BOOK: 'BORROW_BOOK',
  LOGIN: 'LOGIN',

  // Statuses
  SEARCH_SENT: 'SEARCH_SENT',
  SEARCH_WAITING: 'SEARCH_WAITING',
  SEARCH_COMPLETE: 'SEARCH_COMPLETE',
  ADD_SENT: 'ADD_SENT',
  ADD_WAITING: 'ADD_WAITING',
  ADD_COMPLETE: 'ADD_COMPLETE',
  ADD_FAILED: 'ADD_FAILED',
  BORROW_SENT: 'BORROW_SENT',
  BORROW_WAITIG: 'BORROW_WAITIG',
  BORROW_COMPLETE: 'BORROW_COMPLETE',
  BORROW_FAILED: 'BORROW_FAILED',
  AUTHENTICATED: 'AUTHENTICATED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
};
