export default {
  // Action types
  BOOKS: {
    SEARCH:'SEARCH_BOOKS',
    FIND: 'FIND_BOOK',
    LIST: 'LIST_BOOKS',
    LOADING: 'BOOKS_LOADING',
    RESPONSE: 'BOOKS_COMPLETE'
  },
  ADD_BOOK: 'ADD_BOOK',
  LOAN: {
    REQUEST: 'LOAN_REQUEST',
    RESPONSE: 'LOAN_REQUEST',
    LOADING: 'LOAN_LOADING'
  },
  AUTHENTICATION: {
    REQUEST: 'AUTHENTICATION_REQUEST',
    LOADING: 'AUTHENTICATION_WAITING',
    RESPONSE: 'AUTHENTICATION_RESPONSE'
  },
  PERMISSION: {
    GRANTED: 'AUTHORIZED',
    DENIED: 'UNAUTHORIZED'
  },
  ROUTING: {
    GO: 'GO_TO_ROUTE'
  },
  ADD_SENT: 'ADD_SENT',
  ADD_WAITING: 'ADD_WAITING',
  ADD_COMPLETE: 'ADD_COMPLETE',
  ADD_FAILED: 'ADD_FAILED',
  BORROW_SENT: 'BORROW_SENT',
  BORROW_WAITING: 'BORROW_WAITIG',
  BORROW_COMPLETE: 'BORROW_COMPLETE',
  BORROW_FAILED: 'BORROW_FAILED'
};
