export default {
  // Action types
  SEARCH: {
    BOOKS:'SEARCH_BOOKS',
    BOOK: 'SEARCH_BOOK',
    LOADING: 'SEARCH_LOADING',
    RESPONSE: 'SEARCH_COMPLETE'
  },
  ADD_BOOK: 'ADD_BOOK',
  BORROW_BOOK: 'BORROW_BOOK',
  AUTHENTICATION: {
    REQUEST: 'AUTHENTICATION_REQUEST',
    LOADING: 'AUTHENTICATION_WAITING',
    RESPONSE: 'AUTHENTICATION_RESPONSE'
  },
  PERMISSION: {
    GRANTED: 'AUTHORIZED',
    DENIED: 'UNAUTHORIZED'
  },
  ADD_SENT: 'ADD_SENT',
  ADD_WAITING: 'ADD_WAITING',
  ADD_COMPLETE: 'ADD_COMPLETE',
  ADD_FAILED: 'ADD_FAILED',
  BORROW_SENT: 'BORROW_SENT',
  BORROW_WAITING: 'BORROW_WAITIG',
  BORROW_COMPLETE: 'BORROW_COMPLETE',
  BORROW_FAILED: 'BORROW_FAILED'
};
